version: '3'
services:
  proxy:
    build: ./jprox
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./secrets:/srv/secrets
    links:
      - hugo
      - vgrind
  hugo:
    build: ./hugo
    volumes:
      - ./hugo/site:/site
  vgrind:
    build: ./memes/vgrind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
