version: '3.7'
services:
  proxy:
    build: ./jprox
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./secrets:/srv/secrets
    links:
      - hugo
  hugo:
    build: ./hugo
    volumes:
      - type: bind
        source: "./hugo/site"
        target: "/site"
        volume:
          consistency: consistent
