version: '3'
services:
  proxy:
    build: ./jprox
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./secrets:/srv/secrets
    links:
      - hugo
      - vgrind
      - athens
  hugo:
    build: ./hugo
    volumes:
      - ./hugo/site:/site
  vgrind:
    build: ./memes/vgrind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  athens:
    image: gomods/athens:v0.5.0
    volumes:
      - ./storage/athens:/var/lib/athens
    environment:
      - ATHENS_DISK_STORAGE_ROOT=/var/lib/athens
      - ATHENS_STORAGE_TYPE=disk