baseURL = "https://jadendw.dev/"
languageCode = "en-us"
title = "Jaden Weiss"
theme = "binario"

[Params]
  description = "Jaden's Website"
  mainSections = ["posts"]
  mathjax = true
  authorbox = true

[Author]
  name = "Jaden Weiss"
  avatar = "/img/avatar.png"
  copyright = "Jaden Weiss"
  bio = "Just another gopher."

[Params.Social]
  github = "jaddr2line"
  gitlab = "jaddr2line"
  twitter = "jaddr2line"
  mastodon = "https://mst3k.interlinked.me/@jadenw"
  linkedin = "jaden-weiss"
